### ISSUE TITLE
Keep matplotlib version at 1.4.3 for linux installation

### ISSUE THREAD

**Issue by licode** [NSLS-II/PyXRF#53]
I did conda build at Debian 7 virtual machine, and installed pyxrf (conda install -c licode pyxrf) at hxn server. Then the following errors come out when pyxrf is launched. If I replace matplotlib to 1.4.3, everything works file. The new version of matplotlib is 1.5.0 (matplotlib: 1.5.0rc1-np19py27_0), which causes problem.

(pyxrf_oct15)lili@xf03idc-ws2:~$ pyxrf
/home/lili/mc/envs/pyxrf_oct15/lib/python2.7/site-packages/matplotlib/axes/_axes.py:522: UserWarning: No labelled objects found. Use label='...' kwarg on individual plots.
  warnings.warn("No labelled objects found. "
2015-10-27 00:15:21,642 : INFO : Strategy at step 1 is: fit_with_tail
2015-10-27 00:15:21,643 : INFO : Strategy at step 2 is: linear
Traceback (most recent call last):
  File "/home/lili/mc/envs/pyxrf_oct15/bin/pyxrf", line 6, in <module>
    sys.exit(run())
  File "/home/lili/mc/envs/pyxrf_oct15/lib/python2.7/site-packages/pyxrf/gui.py", line 125, in run
    xrfview.show()
  File "/home/lili/mc/envs/pyxrf_oct15/lib/python2.7/site-packages/enaml/widgets/window.py", line 414, in show
    self.initialize()
  File "/home/lili/mc/envs/pyxrf_oct15/lib/python2.7/site-packages/enaml/widgets/window.py", line 192, in initialize
    super(Window, self).initialize()
  File "/home/lili/mc/envs/pyxrf_oct15/lib/python2.7/site-packages/enaml/widgets/toolkit_object.py", line 160, in initialize
    super(ToolkitObject, self).initialize()
  File "/home/lili/mc/envs/pyxrf_oct15/lib/python2.7/site-packages/enaml/core/declarative.py", line 118, in initialize
    child.initialize()
  File "/home/lili/mc/envs/pyxrf_oct15/lib/python2.7/site-packages/enaml/widgets/toolkit_object.py", line 160, in initialize
    super(ToolkitObject, self).initialize()
  File "/home/lili/mc/envs/pyxrf_oct15/lib/python2.7/site-packages/enaml/core/declarative.py", line 118, in initialize
    child.initialize()
  File "/home/lili/mc/envs/pyxrf_oct15/lib/python2.7/site-packages/enaml/widgets/toolkit_object.py", line 160, in initialize
    super(ToolkitObject, self).initialize()
  File "/home/lili/mc/envs/pyxrf_oct15/lib/python2.7/site-packages/enaml/core/declarative.py", line 118, in initialize
    child.initialize()
  File "/home/lili/mc/envs/pyxrf_oct15/lib/python2.7/site-packages/enaml/widgets/toolkit_object.py", line 160, in initialize
    super(ToolkitObject, self).initialize()
  File "/home/lili/mc/envs/pyxrf_oct15/lib/python2.7/site-packages/enaml/core/declarative.py", line 118, in initialize
    child.initialize()
  File "/home/lili/mc/envs/pyxrf_oct15/lib/python2.7/site-packages/enaml/widgets/toolkit_object.py", line 160, in initialize
    super(ToolkitObject, self).initialize()
  File "/home/lili/mc/envs/pyxrf_oct15/lib/python2.7/site-packages/enaml/core/declarative.py", line 118, in initialize
    child.initialize()
  File "/home/lili/mc/envs/pyxrf_oct15/lib/python2.7/site-packages/enaml/widgets/toolkit_object.py", line 159, in initialize
    self.proxy = app.create_proxy(self)
  File "/home/lili/mc/envs/pyxrf_oct15/lib/python2.7/site-packages/enaml/application.py", line 369, in create_proxy
    cls = self.resolve_proxy_class(type(declaration))
  File "/home/lili/mc/envs/pyxrf_oct15/lib/python2.7/site-packages/enaml/application.py", line 347, in resolve_proxy_class
    cls = resolver.resolve(name)
  File "/home/lili/mc/envs/pyxrf_oct15/lib/python2.7/site-packages/enaml/application.py", line 147, in resolve
    return factory()
  File "/home/lili/mc/envs/pyxrf_oct15/lib/python2.7/site-packages/enaml/qt/qt_factories.py", line 164, in mpl_canvas_factory
    from .qt_mpl_canvas import QtMPLCanvas
  File "/home/lili/mc/envs/pyxrf_oct15/lib/python2.7/site-packages/enaml/qt/qt_mpl_canvas.py", line 13, in <module>
    from matplotlib.backends.backend_qt4agg import NavigationToolbar2QTAgg
ImportError: cannot import name NavigationToolbar2QTAgg

**Comment by ericdill** [comment]
This is an enaml bug that is fixed in master.  It was fixed [here] (
https://github.com/nucleic/enaml/pull/189/files).  If you install enaml
from source you can use the new matplotlib (with the new awesome colormaps!)

On Tue, Oct 27, 2015 at 12:35 AM, Li Li <notifications@github.com> wrote:

> I did conda build at Debian 7 virtual machine, and installed pyxrf (conda
> install -c licode pyxrf) at hxn server. Then the following errors come out
> when pyxrf is launched. If I replace matplotlib to 1.4.3, everything works
> file. The new version of matplotlib is 1.5.0 (matplotlib:
> 1.5.0rc1-np19py27_0), which causes problem.
>
> (pyxrf_oct15)lili@xf03idc-ws2:~$ pyxrf
> /home/lili/mc/envs/pyxrf_oct15/lib/python2.7/site-packages/matplotlib/axes/_axes.py:522:
> UserWarning: No labelled objects found. Use label='...' kwarg on individual
> plots.
> warnings.warn("No labelled objects found. "
> 2015-10-27 00:15:21,642 : INFO : Strategy at step 1 is: fit_with_tail
> 2015-10-27 00:15:21,643 : INFO : Strategy at step 2 is: linear
> Traceback (most recent call last):
> File "/home/lili/mc/envs/pyxrf_oct15/bin/pyxrf", line 6, in
> sys.exit(run())
> File
> "/home/lili/mc/envs/pyxrf_oct15/lib/python2.7/site-packages/pyxrf/gui.py",
> line 125, in run
> xrfview.show()
> File
> "/home/lili/mc/envs/pyxrf_oct15/lib/python2.7/site-packages/enaml/widgets/window.py",
> line 414, in show
> self.initialize()
> File
> "/home/lili/mc/envs/pyxrf_oct15/lib/python2.7/site-packages/enaml/widgets/window.py",
> line 192, in initialize
> super(Window, self).initialize()
> File
> "/home/lili/mc/envs/pyxrf_oct15/lib/python2.7/site-packages/enaml/widgets/toolkit_object.py",
> line 160, in initialize
> super(ToolkitObject, self).initialize()
> File
> "/home/lili/mc/envs/pyxrf_oct15/lib/python2.7/site-packages/enaml/core/declarative.py",
> line 118, in initialize
> child.initialize()
> File
> "/home/lili/mc/envs/pyxrf_oct15/lib/python2.7/site-packages/enaml/widgets/toolkit_object.py",
> line 160, in initialize
> super(ToolkitObject, self).initialize()
> File
> "/home/lili/mc/envs/pyxrf_oct15/lib/python2.7/site-packages/enaml/core/declarative.py",
> line 118, in initialize
> child.initialize()
> File
> "/home/lili/mc/envs/pyxrf_oct15/lib/python2.7/site-packages/enaml/widgets/toolkit_object.py",
> line 160, in initialize
> super(ToolkitObject, self).initialize()
> File
> "/home/lili/mc/envs/pyxrf_oct15/lib/python2.7/site-packages/enaml/core/declarative.py",
> line 118, in initialize
> child.initialize()
> File
> "/home/lili/mc/envs/pyxrf_oct15/lib/python2.7/site-packages/enaml/widgets/toolkit_object.py",
> line 160, in initialize
> super(ToolkitObject, self).initialize()
> File
> "/home/lili/mc/envs/pyxrf_oct15/lib/python2.7/site-packages/enaml/core/declarative.py",
> line 118, in initialize
> child.initialize()
> File
> "/home/lili/mc/envs/pyxrf_oct15/lib/python2.7/site-packages/enaml/widgets/toolkit_object.py",
> line 160, in initialize
> super(ToolkitObject, self).initialize()
> File
> "/home/lili/mc/envs/pyxrf_oct15/lib/python2.7/site-packages/enaml/core/declarative.py",
> line 118, in initialize
> child.initialize()
> File
> "/home/lili/mc/envs/pyxrf_oct15/lib/python2.7/site-packages/enaml/widgets/toolkit_object.py",
> line 159, in initialize
> self.proxy = app.create_proxy(self)
> File
> "/home/lili/mc/envs/pyxrf_oct15/lib/python2.7/site-packages/enaml/application.py",
> line 369, in create_proxy
> cls = self.resolve_proxy_class(type(declaration))
> File
> "/home/lili/mc/envs/pyxrf_oct15/lib/python2.7/site-packages/enaml/application.py",
> line 347, in resolve_proxy_class
> cls = resolver.resolve(name)
> File
> "/home/lili/mc/envs/pyxrf_oct15/lib/python2.7/site-packages/enaml/application.py",
> line 147, in resolve
> return factory()
> File
> "/home/lili/mc/envs/pyxrf_oct15/lib/python2.7/site-packages/enaml/qt/qt_factories.py",
> line 164, in mpl_canvas_factory
> from .qt_mpl_canvas import QtMPLCanvas
> File
> "/home/lili/mc/envs/pyxrf_oct15/lib/python2.7/site-packages/enaml/qt/qt_mpl_canvas.py",
> line 13, in
> from matplotlib.backends.backend_qt4agg import NavigationToolbar2QTAgg
> ImportError: cannot import name NavigationToolbar2QTAgg
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NSLS-II-HXN/PyXRF/issues/53>.
>



-- 
Dr. Eric Dill
Assistant Computational Scientist
National Synchrotron Light Source 2

**Comment by ericdill** [comment]
Or I could just build a conda package for the tip of the enaml master branch if you want?

**Comment by licode** [comment]
Thanks. I will also build one in channel licode.
