### ISSUE TITLE
unable to import PyQt4

### ISSUE THREAD

**Issue by rkhyd** [NSLS-II/PyXRF#95]
when i try to run pyxrf, i encounter this error.. please tell me what is the issue?

`(pyxrf_test) root@ip-172-31-25-178:/home/ubuntu# pyxrf
Traceback (most recent call last):
  File "/root/anaconda2/envs/pyxrf_test/bin/pyxrf", line 4, in <module>
    import pyxrf.gui
  File "/root/anaconda2/envs/pyxrf_test/lib/python2.7/site-packages/pyxrf/gui.py", line 38, in <module>
    from enaml.qt.qt_application import QtApplication
  File "/root/anaconda2/envs/pyxrf_test/lib/python2.7/site-packages/enaml/qt/__init__.py", line 35, in <module>
    raise ImportError('Cannot import PyQt4 or PySide')
ImportError: Cannot import PyQt4 or PySide`

**Comment by licode** [comment]
This is due to some conflicts with the new version of qt. In the pyxrf_test environment, run the following line
```
conda install pyqt=4.11
```
Then pyxrf should work.
